### PR TITLE
.

### PR DESCRIPTION
**Pull request by PaltineanuRares956**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Am I missing something? You just deleted some files, right?

**Comment by PaltineanuRares956** [comment]
You mean only from this problem? Because i made some new folders inside my folder for git to separate the problems and now it does not apper the green tick near the files. What should i do?

**Comment by Alex-Cosma** [comment]
Be sure to check all the new files when committing

**Comment by PaltineanuRares956** [comment]
All the new files are all the problems. I put every problem in the folder coresponding to the nr of the course, i will check all of them in a couple of hours.

**Comment by Alex-Cosma** [comment]
Again, everything looks like it's deleted 🤔
Let me check at the lab tomorrow

**Comment by PaltineanuRares956** [comment]
Okk

**Comment by PaltineanuRares956** [comment]
> 
> 
> What is this `vscanf`?

Daca citesc valoarea unei variabile cu scanf intr-o functie, aceasta nu mi se modifica si in main. Am cautat pe net si am gasit vscanf, aparent merge.

**Pull request merged**
